name: Test Action

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  test-run:
    name: Test isolated mode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - uses: ./

  test-run-specific:
    name: Test with specific args
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - uses: ./
        with:
          extra_args: check-yaml

  test-autoupdate:
    name: Test autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - uses: ./
        with:
          command: autoupdate
